/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as InvitacionCodigoRouteImport } from './routes/invitacion.$codigo'
import { Route as ShellSesionesRouteImport } from './routes/_shell.sesiones'
import { Route as ShellGruposRouteImport } from './routes/_shell.grupos'
import { Route as ShellFacturacionRouteImport } from './routes/_shell.facturacion'
import { Route as ShellEstadisticasRouteImport } from './routes/_shell.estadisticas'
import { Route as ShellEntrenadoresRouteImport } from './routes/_shell.entrenadores'
import { Route as ShellConfiguracionRouteImport } from './routes/_shell.configuracion'
import { Route as ShellClientesRouteImport } from './routes/_shell.clientes'
import { Route as ShellBonosRouteImport } from './routes/_shell.bonos'
import { Route as ApiPublicWebhooksWellhubRouteImport } from './routes/api/public/webhooks/wellhub'
import { Route as ApiPublicWebhooksClaspassRouteImport } from './routes/api/public/webhooks/claspass'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const InvitacionCodigoRoute = InvitacionCodigoRouteImport.update({
  id: '/invitacion/$codigo',
  path: '/invitacion/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSesionesRoute = ShellSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGruposRoute = ShellGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFacturacionRoute = ShellFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEstadisticasRoute = ShellEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEntrenadoresRoute = ShellEntrenadoresRouteImport.update({
  id: '/entrenadores',
  path: '/entrenadores',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracionRoute = ShellConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientesRoute = ShellClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBonosRoute = ShellBonosRouteImport.update({
  id: '/bonos',
  path: '/bonos',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicWebhooksWellhubRoute =
  ApiPublicWebhooksWellhubRouteImport.update({
    id: '/api/public/webhooks/wellhub',
    path: '/api/public/webhooks/wellhub',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksClaspassRoute =
  ApiPublicWebhooksClaspassRouteImport.update({
    id: '/api/public/webhooks/claspass',
    path: '/api/public/webhooks/claspass',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bonos': typeof ShellBonosRoute
  '/clientes': typeof ShellClientesRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/entrenadores': typeof ShellEntrenadoresRoute
  '/estadisticas': typeof ShellEstadisticasRoute
  '/facturacion': typeof ShellFacturacionRoute
  '/grupos': typeof ShellGruposRoute
  '/sesiones': typeof ShellSesionesRoute
  '/invitacion/$codigo': typeof InvitacionCodigoRoute
  '/api/public/webhooks/claspass': typeof ApiPublicWebhooksClaspassRoute
  '/api/public/webhooks/wellhub': typeof ApiPublicWebhooksWellhubRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bonos': typeof ShellBonosRoute
  '/clientes': typeof ShellClientesRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/entrenadores': typeof ShellEntrenadoresRoute
  '/estadisticas': typeof ShellEstadisticasRoute
  '/facturacion': typeof ShellFacturacionRoute
  '/grupos': typeof ShellGruposRoute
  '/sesiones': typeof ShellSesionesRoute
  '/invitacion/$codigo': typeof InvitacionCodigoRoute
  '/': typeof ShellIndexRoute
  '/api/public/webhooks/claspass': typeof ApiPublicWebhooksClaspassRoute
  '/api/public/webhooks/wellhub': typeof ApiPublicWebhooksWellhubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_shell/bonos': typeof ShellBonosRoute
  '/_shell/clientes': typeof ShellClientesRoute
  '/_shell/configuracion': typeof ShellConfiguracionRoute
  '/_shell/entrenadores': typeof ShellEntrenadoresRoute
  '/_shell/estadisticas': typeof ShellEstadisticasRoute
  '/_shell/facturacion': typeof ShellFacturacionRoute
  '/_shell/grupos': typeof ShellGruposRoute
  '/_shell/sesiones': typeof ShellSesionesRoute
  '/invitacion/$codigo': typeof InvitacionCodigoRoute
  '/_shell/': typeof ShellIndexRoute
  '/api/public/webhooks/claspass': typeof ApiPublicWebhooksClaspassRoute
  '/api/public/webhooks/wellhub': typeof ApiPublicWebhooksWellhubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cliente'
    | '/perfil'
    | '/reset-password'
    | '/bonos'
    | '/clientes'
    | '/configuracion'
    | '/entrenadores'
    | '/estadisticas'
    | '/facturacion'
    | '/grupos'
    | '/sesiones'
    | '/invitacion/$codigo'
    | '/api/public/webhooks/claspass'
    | '/api/public/webhooks/wellhub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cliente'
    | '/perfil'
    | '/reset-password'
    | '/bonos'
    | '/clientes'
    | '/configuracion'
    | '/entrenadores'
    | '/estadisticas'
    | '/facturacion'
    | '/grupos'
    | '/sesiones'
    | '/invitacion/$codigo'
    | '/'
    | '/api/public/webhooks/claspass'
    | '/api/public/webhooks/wellhub'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/cliente'
    | '/perfil'
    | '/reset-password'
    | '/_shell/bonos'
    | '/_shell/clientes'
    | '/_shell/configuracion'
    | '/_shell/entrenadores'
    | '/_shell/estadisticas'
    | '/_shell/facturacion'
    | '/_shell/grupos'
    | '/_shell/sesiones'
    | '/invitacion/$codigo'
    | '/_shell/'
    | '/api/public/webhooks/claspass'
    | '/api/public/webhooks/wellhub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvitacionCodigoRoute: typeof InvitacionCodigoRoute
  ApiPublicWebhooksClaspassRoute: typeof ApiPublicWebhooksClaspassRoute
  ApiPublicWebhooksWellhubRoute: typeof ApiPublicWebhooksWellhubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/invitacion/$codigo': {
      id: '/invitacion/$codigo'
      path: '/invitacion/$codigo'
      fullPath: '/invitacion/$codigo'
      preLoaderRoute: typeof InvitacionCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/sesiones': {
      id: '/_shell/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof ShellSesionesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/grupos': {
      id: '/_shell/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof ShellGruposRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/facturacion': {
      id: '/_shell/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof ShellFacturacionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/estadisticas': {
      id: '/_shell/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof ShellEstadisticasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/entrenadores': {
      id: '/_shell/entrenadores'
      path: '/entrenadores'
      fullPath: '/entrenadores'
      preLoaderRoute: typeof ShellEntrenadoresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracion': {
      id: '/_shell/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ShellConfiguracionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clientes': {
      id: '/_shell/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ShellClientesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bonos': {
      id: '/_shell/bonos'
      path: '/bonos'
      fullPath: '/bonos'
      preLoaderRoute: typeof ShellBonosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/webhooks/wellhub': {
      id: '/api/public/webhooks/wellhub'
      path: '/api/public/webhooks/wellhub'
      fullPath: '/api/public/webhooks/wellhub'
      preLoaderRoute: typeof ApiPublicWebhooksWellhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/claspass': {
      id: '/api/public/webhooks/claspass'
      path: '/api/public/webhooks/claspass'
      fullPath: '/api/public/webhooks/claspass'
      preLoaderRoute: typeof ApiPublicWebhooksClaspassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellBonosRoute: typeof ShellBonosRoute
  ShellClientesRoute: typeof ShellClientesRoute
  ShellConfiguracionRoute: typeof ShellConfiguracionRoute
  ShellEntrenadoresRoute: typeof ShellEntrenadoresRoute
  ShellEstadisticasRoute: typeof ShellEstadisticasRoute
  ShellFacturacionRoute: typeof ShellFacturacionRoute
  ShellGruposRoute: typeof ShellGruposRoute
  ShellSesionesRoute: typeof ShellSesionesRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBonosRoute: ShellBonosRoute,
  ShellClientesRoute: ShellClientesRoute,
  ShellConfiguracionRoute: ShellConfiguracionRoute,
  ShellEntrenadoresRoute: ShellEntrenadoresRoute,
  ShellEstadisticasRoute: ShellEstadisticasRoute,
  ShellFacturacionRoute: ShellFacturacionRoute,
  ShellGruposRoute: ShellGruposRoute,
  ShellSesionesRoute: ShellSesionesRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvitacionCodigoRoute: InvitacionCodigoRoute,
  ApiPublicWebhooksClaspassRoute: ApiPublicWebhooksClaspassRoute,
  ApiPublicWebhooksWellhubRoute: ApiPublicWebhooksWellhubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
